FROM google/cloud-sdk:alpine

RUN apk add --update --no-cache make ca-certificates openssl && update-ca-certificates

# Installing missing kubectl
RUN gcloud components install --quiet kubectl alpha beta gsutil cloud_sql_proxy && rm -rf /google-cloud-sdk/.install/.backup/ && rm /google-cloud-sdk/bin/kubectl.*

# Getting Helm
RUN wget https://get.helm.sh/helm-v2.16.6-linux-amd64.tar.gz
RUN tar xzf helm-v2.16.6-linux-amd64.tar.gz
RUN mv ./linux-amd64/helm /usr/local/bin/ && mv ./linux-amd64/tiller /usr/local/bin/
RUN rm -f helm-v2.16.6-linux-amd64.tar.gz && rm -rf ./linux-amd64
RUN helm init -c

#Installing plugins

# for GCS support
RUN helm plugin install https://github.com/hayorov/helm-gcs --version 0.2.2

# for Github support
RUN helm plugin install --version master https://github.com/sagansystems/helm-github.git

#for Amazon S3 support
RUN helm plugin install https://github.com/hypnoglow/helm-s3.git

