FROM google/cloud-sdk:alpine

RUN apk add --update make ca-certificates openssl && update-ca-certificates && rm /var/cache/apk/*

# Installing missing kubectl
RUN gcloud components install --quiet kubectl alpha beta gsutil cloud_sql_proxy && rm -rf /google-cloud-sdk/.install/.backup/ && rm /google-cloud-sdk/bin/kubectl.*

# Getting Helm
RUN wget https://get.helm.sh/helm-v2.15.2-linux-amd64.tar.gz
RUN tar xzf helm-v2.15.2-linux-amd64.tar.gz
RUN mv ./linux-amd64/helm /usr/local/bin/ && mv ./linux-amd64/tiller /usr/local/bin/
RUN rm -f helm-v2.15.2-linux-amd64.tar.gz && rm -rf ./linux-amd64
