FROM google/cloud-sdk:alpine

RUN apk add --update --no-cache make ca-certificates openssl && update-ca-certificates

# Installing missing kubectl
# RUN gcloud components install --quiet kubectl alpha beta gsutil cloud_sql_proxy && rm -rf /google-cloud-sdk/.install/.backup/ && rm /google-cloud-sdk/bin/kubectl.*
RUN gcloud components install --quiet alpha beta gsutil cloud_sql_proxy && rm -rf /google-cloud-sdk/.install/.backup/
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && ./kubectl version --client && \
    mv ./kubectl /usr/local/bin/ && rm /usr/local/bin/docker

# Getting Helm
RUN wget https://get.helm.sh/helm-v3.7.0-linux-amd64.tar.gz
RUN tar xzf helm-v3.7.0-linux-amd64.tar.gz
RUN mv ./linux-amd64/helm /usr/local/bin/
RUN rm -f helm-v3.7.0-linux-amd64.tar.gz && rm -rf ./linux-amd64
RUN rm -rf /var/lib/apt/lists

# Adding default repo
RUN helm repo add stable https://charts.helm.sh/stable

#Installing plugins

# for GCS support
RUN helm plugin install https://github.com/hayorov/helm-gcs

# for Github support
RUN helm plugin install --version master https://github.com/sagansystems/helm-github.git

#for Amazon S3 support
RUN helm plugin install https://github.com/hypnoglow/helm-s3.git
