FROM google/cloud-sdk:alpine

RUN apk add --update --no-cache make ca-certificates openssl && update-ca-certificates

# Installing missing kubectl
RUN gcloud components install --quiet kubectl alpha beta gsutil cloud_sql_proxy && rm -rf /google-cloud-sdk/.install/.backup/ && rm /google-cloud-sdk/bin/kubectl.*

# Getting Helm
RUN wget https://get.helm.sh/helm-v3.2.0-linux-amd64.tar.gz
RUN tar xzf helm-v3.2.0-linux-amd64.tar.gz
RUN mv ./linux-amd64/helm /usr/local/bin/
RUN rm -f helm-v3.2.0-linux-amd64.tar.gz && rm -rf ./linux-amd64

# Adding default repo
RUN helm repo add stable https://kubernetes-charts.storage.googleapis.com/

#Installing plugins

# for GCS support
RUN helm plugin install https://github.com/hayorov/helm-gcs

# for Github support
RUN helm plugin install --version master https://github.com/sagansystems/helm-github.git

#for Amazon S3 support
RUN helm plugin install https://github.com/hypnoglow/helm-s3.git

